apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grammr-dev
resources:
  - release.yaml
configMapGenerator:
  - name: clerk-jwt-public-key
    files:
      - jwt-key.pub=jwt-key.pub
  - name: core-values-cm
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml