apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grammr-dev
resources:
  - release.yaml
configMapGenerator:
  - name: core-values-cm
    files:
      - values.yaml=values.yaml
secretGenerator:
  - name: grammr-values
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml